// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC52xrIl16ydG_ZRixLdxjcWf-Q-Ksiw8',
    appId: '1:827387974113:web:fc93b3add549832f2682a0',
    messagingSenderId: '827387974113',
    projectId: 'krok-test-1bcc2',
    authDomain: 'krok-test-1bcc2.firebaseapp.com',
    storageBucket: 'krok-test-1bcc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHARZ7u358vgADQ_f1Fjq9FB0PwWa1hQQ',
    appId: '1:827387974113:android:22f0775572204d2c2682a0',
    messagingSenderId: '827387974113',
    projectId: 'krok-test-1bcc2',
    storageBucket: 'krok-test-1bcc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0G7TDTKkO0kJu3BsLbOdffSJtR0eg0DI',
    appId: '1:827387974113:ios:eb256b049f550faa2682a0',
    messagingSenderId: '827387974113',
    projectId: 'krok-test-1bcc2',
    storageBucket: 'krok-test-1bcc2.appspot.com',
    iosBundleId: 'com.kroktesttask.krokTestTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0G7TDTKkO0kJu3BsLbOdffSJtR0eg0DI',
    appId: '1:827387974113:ios:606451fa7e58a4982682a0',
    messagingSenderId: '827387974113',
    projectId: 'krok-test-1bcc2',
    storageBucket: 'krok-test-1bcc2.appspot.com',
    iosBundleId: 'com.kroktesttask.krokTestTask.RunnerTests',
  );
}
